### ISSUE TITLE
Mirrorfor the 2nd time 

### ISSUE THREAD

**Issue by HB9SIU** [w4mmp/MSCC-PW#6] opened 2022-08-28 10:31 UTC
W4MNp de HB9SIU John.

Hello Ron,
I apologize for addressing my problem again
report to you.

In your mail of 8/21/2022
Re: [w4mmp/MSCC-PW] mirror and delay (Issue #3)
you ask me questions

I tried this question with a number of
Files (images of spectra) and the file: "mirrror" to be answered at GitHub.

So you can see for yourself where I put my pictures and the file on gitHub
Attached is an image copy from my GitHub account.

Question: Does this information appear in the expected place in GitHub?

Do NOT take my message as leverage.
I'm just not sure yet if I can send my reports to the
right place, publish in the right way on github.

My message regarding "mirror" has not changed here for me.

The phenomenon of insufficient image rejection is like me
in the meantime researched and read on the net, a well-known one
and not an easy problem to solve.
Very small errors in magnitude and/or phase
in the processing of the two signals I and Q lead to insufficient
suppression of the image frequency.

Because the phenomenon of insufficient image frequency suppression
under the "MSCC" software, I did not notice it for a short time
installed and activated this older software.
The phenomenon also occurs here.
I didn't notice it at the time.

Now here with me again "MSC-PW" active with the latest firmware.

In the meantime it is clear to me that with the tools (Tab Freq Cal)
"RX I/Q calibration" and (Tab S/F) "TX I/Q calibration" error in signal processing
of I and Q are trying to correct, so that
the image frequency suppression is sufficient for both transmission and reception.

In the older "MSCC Operators Guide" (06/14/20 it is on page 15 ff
described.
These procedures for the new MSCC-PW software are still in the new operating manual.

I tried following the old manual that described
steps to be carried out with the new software as well.
Unfortunately without success.
The sliders for minimizing IQ errors show from -200 to +200 in one step
(increment =1) NO influence on the image display (spectrum)

In the old manual, on page 18 under "Note 3" it says -43 dB or better
spoken. Halleluia.

Question : Am I the only user complaining about this phenomenon 

====================================================

Image below: Snipping from GitHub  Does content and location make sense?

![GitHub_after_login](https://user-images.githubusercontent.com/45912766/187069216-db1e67e1-4fc8-45cf-bf42-f448a618c6da.JPG)
?

**Comment by N8VET** [comment] 2022-08-28 14:52
Hi John,

I was able to find your fork to view the images.  Unless your zoomed in the image it is more like 24khz away as expected.  Although the image intensity is very high.  This issue has not been reported nor have I experienced this issue.  Any image that might be there is very low and easily adjusted with I/Q balance correction.  The default RX I/Q correction is usually pretty good with image not visible unless you inject a very strong signal.

1.  Could you download and install latest version of MSCC-PW.  Go to MSCC-PW shortcut on desktop and open utilities folder.  Double click on backup-logfiles.exe and attach zipped logs to github so I can view it.
2.  Make sure you are running latest firmware in Proficio, 122.1
3.  I may have missed it, but do you try HDSDR and check for the same images?  Make sure you reset the calibration settings.  With an image this strong, and in my experience, this is caused by hardware issue so trying HDSDR with help confirm or deny it is a hardware problem.

Stew
N8VET

**Comment by HB9SIU** [comment] 2022-08-28 16:55
first my log-files
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/9440093/ziplog.zip)

Comment for Stew follows later. 73 de HB9SIU / John   many thanks for your manpower

**Comment by N8VET** [comment] 2022-08-28 19:06
Thank you for the logs.  They show sdrcore-trans is failing.  You should be getting an error message?
1.  Make sure windows audio has not set any multus audio device to default.
2.  go to the same utilities folder and run audio-reset.exe
3. Restart MSCC-PW.  The only pop up windows should be one for frequency calibration and another for QRP power calibration. 
Stew
N8VET

**Comment by HB9SIU** [comment] 2022-08-29 18:10
Dear Ron,   dear Stew,

With a probability bordering on certainty I have found the error.

In the schematic part called "Frontend" there is U6.1 or U6.2 at the output of the IC
one jumper each JP3 or JP5.
 
 A jumper is set to connect the two pins .
The other jumper is set so that the two pins are not connected together.

And that must not be.

In my opinion, both jumpers should be set the same.

Question how must the two Junper be set?

a) so that the two jumpers connect the pins or
b) that the two pins are not connected.

However,
thank you very much for your help or
as Ron writes at the end of every email:

"Tank you for your support and business"  Hi

73 de HB9SIU / John

**Comment by N8VET** [comment] 2022-08-29 20:52
Hi John,

That is the issue.  Those headers are to change the gain of the RX opamp and they need to be same, on or off.  Off is the normal position. 

The result was audio channels where not equal amplitudes resulting in IQ balance error.  Good catch.  I need to add that to my troubleshooting tree:)

Stew
N8VET

**Comment by w4mmp** [comment] 2022-08-31 16:54
Hi John,
What is the status of your radio?  Has the image issue been resolved?  Is MSCC-PW now starting as it should?
Ron
W4MMP

**Comment by HB9SIU** [comment] 2022-08-31 19:12
Hello Ron,

Sorry for my late reply.

Issue #3 and #6 can be closed.

problems are solved.

a) The image frequency suppression on the 80m Band
is 50dB.    Great success.

b) The problem that MSCC occurs with a time delay
responds to commands, I can no longer provoke.
(not determinable at the moment).

Hardware and software ok.

Again many thanks for the help.

best 73 de HB9SIU / John

**Comment by w4mmp** [comment] 2022-08-31 19:23
Hi John,
No problem and you are most welcome.  I'm very glad things are now in working order.
I will close this issue.
73,
Ron
W4MMP

**Closed as completed by w4mmp** 2022-08-31 19:23 UTC

**Comment by N8VET** [comment] 2022-10-11 07:02
Hi John,That is the issue.  Those headers are to change the gain the RX opamp and they need to be same, on or off.  Off is the normal position. The result was audio channels where not equal amplitudes resulting in IQ balance error.  Good catch.  I need to add that to my troubleshooting:)StewN8VETSent from my Galaxy
-------- Original message --------From: John Troesch ***@***.***> Date: 8/29/22  14:10  (GMT-05:00) To: w4mmp/MSCC-PW ***@***.***> Cc: N8VET ***@***.***>, Comment ***@***.***> Subject: Re: [w4mmp/MSCC-PW] Mirrorfor the 2nd time  (Issue #6) 
Dear Ron,   dear Stew,
With a probability bordering on certainty I have found the error.
In the schematic part called "Frontend" there is U6.1 or U6.2 at the output of the IC
one jumper each JP3 or JP5.
A jumper is set to connect the two pins .
The other jumper is set so that the two pins are not connected together.
And that must not be.
In my opinion, both jumpers should be set the same.
Question how must the two Junper be set?
a) so that the two jumpers connect the pins or
b) that the two pins are not connected.
However,
thank you very much for your help or
as Ron writes at the end of every email:
"Tank you for your support and business"  Hi
73 de HB9SIU / John
