### ISSUE TITLE
Latency of frequency changes after continued TX

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#24] opened 2022-11-07 19:25 UTC
I installed the 11/16 .exe and ran MSCC-PW until I got latency and immediately created a backup and ziplog which is attached.  When I tried to EXT, the console disappeared but rx remained as did the spectrum and waterfall.  A GUI error message came up saying no communication with Console and programmed fully closed.
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10025584/ziplog.zip)

On continued use for making cw contacts I have experienced latency in changing frequency lasting a few seconds.  Exiting and restart restored normal operation.

**Comment by w4mmp** [comment] 2022-11-11 17:13
Hi Bob,
When this occurs, please turn off you virus protection, _temporarily_ BEFORE stopping MSCC-PW.  Does the problem persist?
73,
Ron

**Comment by BobW9BF** [comment] 2022-11-11 17:53
Ron,Will report back on next occurrence if pausing Defender prevents reoccurrence.  I notice latency occurring when i make frequent band changes.  I need to find a repeatable cause. On Nov 11, 2022, at 11:14 AM, W4MMP ***@***.***> wrote:﻿
Hi Bob,
When this occurs, please turn off you virus protection, temporarily BEFORE stopping MSCC-PW.  Does the problem persist?
73,
Ron

**Comment by BobW9BF** [comment] 2022-11-12 23:07
Ron,

I just ran into the latency issue with frequency change.  I turned off the
virus protection and found latency still present.  I shut down MSCC and
found normal operation on restart.  Is this the protocol you prescribed?  I
did not turn the virus protection before or after restart.

73, Bob

**Comment by w4mmp** [comment] 2022-11-15 14:23
Hi Bob,
I'm testing a new version that attempts to catch this condition and make reports to the logs of the slow down.  I will not have a fix until I can catch the condition that causes it.  My gut feeling is the issue relates to a networking issue, but I'm not sure.  It could have something to do with a slow file update but again I don't really know.  
Thanks for running through the procedure.   That more or less rules out virus protection being the cause.
73,
Ron

**Comment by BobW9BF** [comment] 2022-11-15 14:35
Thanks for the update, Ron.  I continue to enjoy my Ultimus.73, BobOn Nov 15, 2022, at 8:23 AM, W4MMP ***@***.***> wrote:﻿
Hi Bob,
I'm testing a new version that attempts to catch this condition and make reports to the logs of the slow down.  I will not have a fix until I can catch the condition that causes it.  My gut feeling is the issue relates to a networking issue, but I'm not sure.  It could have something to do with a slow file update but again I don't really know.
Thanks for running through the procedure.   That more or less rules out virus protection being the cause.
73,
Ron

**Comment by w4mmp** [comment] 2022-11-17 16:36
I have examined the log files and my debugging routine did not reveal anything.   This is going to be a tough one to track down.
73,
Ron

**Comment by Bob-TX** [comment] 2022-11-17 21:57
Ron, I have observed the lag is response to user input with MSCC-PW with MSCC-PW: MSCC-PW-Install-20221116.exe and all versions from the last couple of months. It seems to occur after frequent changes to settings in the program, i.e. multiple band changes, filter selections or tuning across a band for several minutes. Once it occurs, continued use of the program seems to increase the delay in response until finally the error screen comes up saying there is no response between one of the portions of the program.
Today, using the newest version with the debugging features I was able to get it to happen after about a half-hour of using the software. The symptoms I observe is the MAIN tab (upper portion of the screen - NOT the spectrum or waterfall portions) continue to respond immediately to user inputs (clicking or mouse scroll) however the audio of the received signals do not change for 4 to about 6 seconds after the user input is done, and then even more delay (usually 3 to 6 seconds for a total delay of 11 to 13 seconds) occurs before the spectrum and waterfall display the new signals. I have had the program become unresponsive to user input, i.e. what I hear in the received audio and see on the spectrum and waterfalls do not match what I know to be on the frequency selected in the top window area. This last symptom usually occurs after the delays seem to increase and often result in the 'loss of communication with the spectrum and/or waterfall' error window. Changing bands seems to restore the operation but does not eliminate the delays.
I did produce a log file before exiting MSCC-PW and will attach it below. I did not capture audio or video recordings of these symptoms but I can if they will help you understand my reports in the future. One tip on seeing the delays.....tune in the digital signals (FT8, etc.) on a busy band and tune away and back by using the 10 kHz digit with the mouse wheel. The 10 k
Hz jumps in frequency are easy to see on the spectrum and waterfall and the audio will confirm if the system is responding quickly....or not.

[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10036015/ziplog.zip)

Thanks Ron!
Bob, AF5Z

**Comment by w4mmp** [comment] 2022-11-18 18:07
Hi Bob,
Thanks for the info.  Still trying to track this down.
73,
Ron

**Comment by Bob-TX** [comment] 2022-11-24 18:15
I installed MSCC-PW MSCC-PW-Install-20221124.exe this morning and was not able to see the latency/delayed response symptoms until I transmitted a few times with semi-breakin CW. After that I see delay when I tune by changing the 10 Khz digit on the MAIN frequency window - - the receiver continues to hear the existing signals for several seconds even though the 10 Khz digit responds immediately to mouse scrolls, - once the receiver tunes to the new frequency it takes several seconds for the spectrum and waterfall to display the new received signals. Once I see the delays, I've been unable to correct the issue by changing frequency, filter selection, band selection or mode selection - - only a EXT and re-start of MSCC-PW corrects the issue and there are no more latency/delay symptoms.
I waited a few minutes after observing the delays before doing a BACKUP to generate a C:\MSCC-PW\ziplog.zip file which is attached below.
I understand that you are working on the issue, I'm providing additional information and a logfile to help you. Thanks Ron!
Bob, AF5Z
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10086739/ziplog.zip)

When the latency/delay condition exists, clicking EXT immediately produces the "Stop MSCC?  YES NO" window however clicking on YES immediately closes the MAIN GUI window and leaves both the spectrum and waterfall windows. Today this delayed over ten seconds and finally I got the "MSCC GUI window is not responding" (or similar) window and I clicked to STOP/CLOSE MSCC-PW. In my opinion, the software system is having difficulty exiting and closing likely due to the latency/delayed response symptom.

**Comment by BobW9BF** [comment] 2022-11-24 18:51
I'm just behind Bob, AF5Z, in running into the multi-second latency response to mouse frequency changes after a period of use on 15m.  Attached is my ziplog file.  Fingers crossed for easy fix.

Happy Turkey Day,
Bob W9BF
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10086855/ziplog.zip)

**Comment by Bob-TX** [comment] 2022-11-25 16:04
The delayed response still occurs with MSCC-PW-Install-20221124.exe. It seems to happen only after one or more CW transmissions. I followed your instructions to click the "KEEP ALIVE" check box after it happend and then allow MSCC-PW to run another five minutes or so before clicking the BACKUP box.
The logfile is attached  
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10094071/ziplog.zip)

Thank you for your work on this Ron. I believe Bob, W9BF accidentally closed this issue on GitHub yesterday however the issue still exists.
Bob, AF5Z

**Comment by w4mmp** [comment] 2022-11-25 17:30
Hi Bob,
Thanks.  I will examine the logs.
73,
Ron

**Comment by w4mmp** [comment] 2022-11-25 17:37
Hi,
Please try again but this time when you click on "KEEP ALIVE", _**do not**_ navigate anywhere else.  Simply let it run for 5 minutes or so and the click the back up button.  Then you may navigate back to the main tab and stop MSCC-PW.

**Comment by BobW9BF** [comment] 2022-11-25 18:22
I experienced frequency change latency after changing bands and transmitting.  Per instructions I then clicked on Keep Alive and waited five minutes before clicking on Backup.  

Attached is the ziplog folder having today's date.
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10094617/ziplog.zip)

**Comment by w4mmp** [comment] 2022-11-25 19:46
Hi Bob,
This looks like a networking issue.   The logs reveal dropped UDP packets (not many but they are dropped).  
What other network applications are running while MSCC-PW is running (browser, email client and such)?  I may need to switch to TCP verses UDP as the network transport protocol.  
73,
Ron

**Comment by Bob-TX** [comment] 2022-11-25 21:30
Hi Ron,
In an effort to eliminate possible causes....I powered off my PC, disconnected the ethernet network cable, powered back on and booted up, ran MSCC-PW, selected 21 Mhz Band & USB mode, noted tuning was instant and no delays were occurring, clicked the PTT box on the MAIN windows a couple of times to switch from receive to transmit and back, then I notice delayed response. I went to SYSTEM and clicked KEEP ALIVE, waited about 4 minutes with SYSTEM screen still up and no other clicks or changes to MSCC functions - then clicked BACKUP to generate the log file.
My PC is a desktop unit with no bluetooth or WiFi network interfaces. Removing the ethernet cable insures no connection to the internet. I also did not run any email client or web browser during the above steps - obviously neither will work without a network cable. I realize that the Windows networking software stacks are still functional but at least my procedure should eliminate my network (router, cables & ethernet switch).
I then re-connected the ethernet cable and made this comment and uploaded the log file.
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10095137/ziplog.zip)

Thanks for your help Ron. If you need me to try anything else, just ask.
Bob, AF5Z

**Comment by BobW9BF** [comment] 2022-11-25 22:03
Ron,

Bob, AF5Z, got latency with no network applications whereas I have a
router-based network that has numerous devices connected... phones, tv, two
computers, wireless bridges.... The computer I run MSCC-PW on has lots of
traffic on Firefox tabs that have programs getting updated internet data
(wx, DX clusters, time sync, etc).  I have one computer that is clean of
programs but run Virtual Box on it for Windows legacy programs.

Standing by to test options....  and thanks for all the work you're doing
on our behalf and others...

Bob 'BF

**Comment by w4mmp** [comment] 2022-11-26 03:18
Hi Guys,
Please do a favor for me.   Start MSCC-PW, tune around, change bands, operation mode (usb,etc), but _**do not**_ transmit.  No PTT or TUN or CW keying.  I need to see if the issue is related to TX mode (or not).  In other words keep MSCC-PW in receive mode, no TX of any type.

**Comment by Bob-TX** [comment] 2022-11-26 15:28
I've listened to both CW and SSB on 40m, 30m CW, 20m, 17m, 15m, 12m & 10m for more than an hour, changing modes and bands frequently but I'm unable to get MSCC-PW to show the latency/delay symptom.
I clicked KEEP ALIVE, waited 5 minutes and clicked BACKUP.......Here's the logfile.
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10096500/ziplog.zip)

The above log file was produced when there was no discernible latency/delay.
Bob, AF5Z

**Comment by BobW9BF** [comment] 2022-11-26 15:29
Per your instructions I spent 15 minutes changing bands, modes, frequency
and found no latency.  I then made four short transmissions and Ultimus
went into latency behavior.  Later I will put toroids on all lines and see
if that mitigates the issue.  Could be an rfi fix will be the answer.

**Comment by Bob-TX** [comment] 2022-11-26 15:32
After the previous comment I exited MSCC-PW and then re-started it. While listening to 15m CW, I clicked the TUN box about three times to produce a 1w carrier and noted that there was no latency/delay after each time. I then tried turning SEMI-BREAKIN OFF and clicking the PTT BOX about five times, at first there was no latency/delay however after 3 to 5 times, the delay symptom re-appeared. I then clicked the KEEP ALIVE box, waited 5 minutes and then clicked BACKUP to create the log file below.
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/10096523/ziplog.zip)

The above logfile shows the latency/delay symptom.
Bob, AF5Z

**Comment by w4mmp** [comment] 2022-11-26 16:53
Hi Bob, AF5Z,
Which transceiver do you have?
73,
Ron

**Comment by w4mmp** [comment] 2022-11-26 17:11
Eureka!  I can recreate the issue at will!  The common thread is CW plus PTT.   In CW mode and pressing the PTT button several times, the latency is produced.  Now I need to take a look at the CW routine(s) and find out why this is happening.
73,
Ron

**Comment by Bob-TX** [comment] 2022-11-26 17:25
Proficio 5w

**Comment by Bob-TX** [comment] 2022-11-26 17:27
Good job, Ron. Thanks for communicating well & staying with it.

Let us know if you need additional tests done or questions answered.

Bob, AF5Z

**Comment by w4mmp** [comment] 2022-11-30 14:57
Hi Folks,
Just to keep you informed.  Stew is also able to create the issue at will.   I am now convinced it is NOT a networking related issue.   There is a specific set of conditions that trigger a logic error somewhere deep in the code.  I will continue to work the issue until I find a resolution.

**Comment by w4mmp** [comment] 2023-03-08 01:58
This issue is now resolved.  There was a bug in the ALC reporting routine.
A new release is available on the Proton drive.

**Closed as completed by w4mmp** 2023-03-08 01:58 UTC
